GET http://localhost:8030/courses-counter

### Send POST request with json body
PUT http://localhost:8030/courses/d1b04d1e-ab69-4a0e-b3aa-bdacdebc91f3
Content-Type: application/json

{
  "name": "perron",
  "duration": "2d"
}


###
# ELASTIC - Search
POST localhost:9200/backoffice_courses/_searchh
Content-Type: application/json

{
  "query": {
    "term": {
      "name": "Pepe"
    }
  }
}

###
# ELASTIC - Search
POST localhost:9200/backoffice_courses/_search
Content-Type: application/json

###

