framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  LuisCusihuaman\Tests\:
    resource: '../../../../tests/src'

  LuisCusihuaman\Shared\Domain\RandomNumberGenerator: '@LuisCusihuaman\Tests\Shared\Infrastructure\ConstantRandomNumberGenerator'
