framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  LuisCusihuaman\Tests\:
    resource: '../../../../tests/src'

  LuisCusihuaman\Shared\Domain\RandomNumberGenerator: '@LuisCusihuaman\Tests\Shared\Infrastructure\ConstantRandomNumberGenerator'

  LuisCusihuaman\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [ !tagged luiscusihuaman.database_connection ]

  # IMPLEMENTATIONS SELECTOR, must APP_ENV=test

  #  LuisCusihuaman\Shared\Domain\Bus\Command\CommandBus: '@LuisCusihuaman\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus'
  #  LuisCusihuaman\Shared\Domain\Bus\Query\QueryBus: '@LuisCusihuaman\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus'
  LuisCusihuaman\Shared\Domain\Bus\Event\EventBus: '@LuisCusihuaman\Shared\Infrastructure\Bus\Event\MySql\MySqlDoctrineEventBus' #RabbitMqEventBusTest.php#47
