imports:
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_database.yaml }
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  _instanceof:
    LuisCusihuaman\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: [ 'luiscusihuaman.domain_event_subscriber' ]

  LuisCusihuaman\Apps\Mooc\Backend\Controller\:
    resource: '../src/Controller'
    tags: [ 'controller.service_arguments' ]

  LuisCusihuaman\:
    resource: '../../../../src'

  # Dependencies
  LuisCusihuaman\Shared\Infrastructure\Bus\Event\SymfonySyncEventBus:
    arguments: [ !tagged luiscusihuaman.domain_event_subscriber ]

  LuisCusihuaman\Shared\Infrastructure\Bus\Event\DomainEventMapping:
    arguments: [ !tagged luiscusihuaman.domain_event_subscriber ]

  LuisCusihuaman\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [ !tagged luiscusihuaman.database_connection ]

  LuisCusihuaman\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  # Instance selector
  LuisCusihuaman\Shared\Domain\Bus\Event\DomainEventPublisher: '@LuisCusihuaman\Shared\Infrastructure\Bus\Event\SymfonySyncDomainEventPublisher'
