services:
  _defaults:
    autoconfigure: true
    autowire: true


  LuisCusihuaman\Apps\Mooc\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  LuisCusihuaman\:
    resource: '../../../../src'
