imports:
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_database.yaml }
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Configure
  _instanceof:
    LuisCusihuaman\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: [ 'luiscusihuaman.domain_event_subscriber' ]

  LuisCusihuaman\Apps\Mooc\Backend\Controller\:
    resource: '../src/Controller'
    tags: [ 'controller.service_arguments' ]

  LuisCusihuaman\Apps\Mooc\Backend\Command\:
    resource: '../src/Command'
    tags: [ 'console.command' ]

  # Wire
  LuisCusihuaman\:
    resource: '../../../../src'

  # Dependencies
  LuisCusihuaman\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [ !tagged luiscusihuaman.domain_event_subscriber ]
    # https://symfony.com/doc/current/service_container/lazy_services.html
    lazy: true

  LuisCusihuaman\Shared\Infrastructure\Bus\Event\DomainEventMapping:
    arguments: [ !tagged luiscusihuaman.domain_event_subscriber ]

  LuisCusihuaman\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
    arguments: [ !tagged luiscusihuaman.domain_event_subscriber ]

  LuisCusihuaman\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [ !tagged luiscusihuaman.database_connection ]

  LuisCusihuaman\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  LuisCusihuaman\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus:
    arguments: [ '@LuisCusihuaman\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection', '%env(RABBITMQ_EXCHANGE)%' ]

  LuisCusihuaman\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqDomainEventsConsumer:
    arguments:
      - '@LuisCusihuaman\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection'
      - '@LuisCusihuaman\Shared\Infrastructure\Bus\Event\DomainEventJsonDeserializer'
      - '%env(RABBITMQ_EXCHANGE)%'
      - '%env(RABBITMQ_MAX_RETRIES)%'

  LuisCusihuaman\Apps\Mooc\Backend\Command\RabbitMq\ConfigureRabbitMqCommand:
    arguments:
      - '@LuisCusihuaman\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConfigurer'
      - '%env(RABBITMQ_EXCHANGE)%'
      - !tagged luiscusihuaman.domain_event_subscriber

  # -- APP DEFINITIONS --
  # RabbitMQ
  LuisCusihuaman\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection:
    arguments:
      - host: '%env(RABBITMQ_HOST)%'
        port: '%env(RABBITMQ_PORT)%'
        vhost: '%env(RABBITMQ_MOOC_VHOST)%'
        login: '%env(RABBITMQ_LOGIN)%'
        password: '%env(RABBITMQ_PASSWORD)%'
        read_timeout: 2
        write_timeout: 2
        connect_timeout: 5

  # IMPLEMENTATIONS SELECTOR, also APP_ENV must be 'dev'
  LuisCusihuaman\Shared\Domain\Bus\Event\EventBus: '@LuisCusihuaman\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus'
