services:
  _defaults:
    autoconfigure: true
    autowire: true


  LuisCusihuaman\Apps\Mooc\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  LuisCusihuaman\:
    resource: '../../../../src'

  LuisCusihuaman\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
