courses_get:
  path: /courses
  controller: LuisCusihuaman\Apps\Backoffice\Backend\Controller\Courses\CoursesGetController
#  defaults: { auth: true } # 👈 turn up auth module in this route
  methods:  [GET]
