courses_get:
  path: /courses
  controller: LuisCusihuaman\Apps\Backoffice\Frontend\Controller\Courses\CoursesGetController
  methods:  [GET]

courses_post:
  path: /courses
  controller: LuisCusihuaman\Apps\Backoffice\Frontend\Controller\Courses\CoursesPostController
  methods:  [POST]
